'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export function LoginForm({ title, redirect, expectedRole }: { title: string; redirect: string; expectedRole?: string }) {
  const router = useRouter(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) { setError(result.error || 'Unable to sign in.'); setLoading(false); return; } if (expectedRole && result.role !== expectedRole) { setError('This account does not have access to this portal.'); setLoading(false); await fetch('/api/auth/logout', { method: 'POST' }); return; } router.push(redirect); }
  return <div className="auth-card"><a className="brand" href="/"><span className="mark">R</span>Dr. Rashida Ahmad</a><div className="eyebrow" style={{marginTop:32}}>Secure access</div><h1 style={{fontSize:42,margin:'12px 0 22px'}}>{title}</h1><form onSubmit={submit}><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" required autoComplete="email" /></div><div className="field"><label htmlFor="password">Password</label><input id="password" name="password" type="password" required autoComplete="current-password" /></div>{error && <div className="form-error">{error}</div>}<button className="btn primary" style={{width:'100%',marginTop:20}} disabled={loading}>{loading ? 'Signing in...' : 'Sign in'}</button></form><p className="muted" style={{fontSize:12,marginTop:22}}>Development accounts are created by the server seed process. Credentials are never rendered into the frontend.</p></div>;
}
