import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getServerSession, safeServerFetch } from '@/lib/api/server';
import { SignOutButton } from '@/components/sign-out-button';

export const dynamic = 'force-dynamic';

type PatientAppointment = any; // eslint-disable-line @typescript-eslint/no-explicit-any

export default async function PatientDashboard() { const session = await getServerSession(); if (!session || session.role !== 'PATIENT') redirect('/login'); const appointmentsData = await safeServerFetch<{ appointments: PatientAppointment[] }>('/api/appointments', { appointments: [] }, 'patient/appointments'); const appointments=appointmentsData?.appointments||[]; return <div className="dash"><div className="dashbar"><div className="container nav"><Link className="brand" href="/"><span className="mark">R</span>Dr. Rashida Ahmad</Link><div className="actions"><span>{session.name}</span><SignOutButton /></div></div></div><main className="container dashmain"><div className="eyebrow">Patient portal</div><h1 style={{fontSize:48,marginTop:12}}>Your care, in one place.</h1><div className="stats"><div className="stat"><span>Upcoming</span><strong>{appointments.filter(item=>['PENDING','CONFIRMED'].includes(item.status)).length}</strong></div><div className="stat"><span>Completed</span><strong>{appointments.filter(item=>item.status==='COMPLETED').length}</strong></div><div className="stat"><span>Appointments</span><strong>{appointments.length}</strong></div><div className="stat"><span>Account</span><strong>Active</strong></div></div><div className="dashgrid"><section className="list-card"><div className="section-head"><div><div className="eyebrow">My appointments</div><h2 style={{fontSize:32,marginTop:8}}>Your schedule</h2></div><Link className="btn primary" href="/book">New booking</Link></div>{appointments.length ? appointments.map(item=><div className="appointment" key={item.id}><div><b>{item.service?.name || 'Unknown service'}</b><br/><small className="muted">{item.localDate} · {item.localTime} IST · {item.consultationType}</small></div><div><span className="badge">{item.status}</span><br/><small className="muted">{item.bookingId}</small></div></div>) : <p className="muted">No appointments yet.</p>}</section><aside className="list-card"><div className="eyebrow">My profile</div><h3 style={{marginTop:12}}>{session.name}</h3><p className="muted">{session.email}</p><p className="disclaimer">Your personal and health information is protected by server-side authorization.</p></aside></div></main></div>; }
