CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "Role" AS ENUM ('ADMIN', 'DOCTOR', 'PATIENT');
CREATE TYPE "AppointmentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'IN_CONSULTATION', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW');
CREATE TYPE "PaymentStatus" AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'NOT_REQUIRED');
CREATE TYPE "NotificationChannel" AS ENUM ('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP');
CREATE TYPE "NotificationStatus" AS ENUM ('QUEUED', 'PROCESSING', 'SENT', 'DELIVERED', 'FAILED');

CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL,"name" TEXT NOT NULL,"phone" TEXT,"isActive" BOOLEAN NOT NULL DEFAULT true,"forcePasswordChange" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PatientProfile" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"age" INTEGER,"gender" TEXT,"city" TEXT,"consentAt" TIMESTAMP(3),CONSTRAINT "PatientProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DoctorProfile" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"displayName" TEXT NOT NULL,"qualification" TEXT,"specialization" TEXT,"experience" TEXT,"bio" TEXT,"languages" TEXT[],"clinicAddress" TEXT,"timezone" TEXT NOT NULL DEFAULT 'Asia/Kolkata',"onlineFee" INTEGER NOT NULL DEFAULT 0,"clinicFee" INTEGER NOT NULL DEFAULT 0,"durationMinutes" INTEGER NOT NULL DEFAULT 30,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "DoctorProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Service" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"description" TEXT NOT NULL,"durationMin" INTEGER NOT NULL,"fee" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Service_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AvailabilityRule" ("id" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"weekday" INTEGER NOT NULL,"startTime" TEXT NOT NULL,"endTime" TEXT NOT NULL,"breakStart" TEXT,"breakEnd" TEXT,"slotMinutes" INTEGER NOT NULL DEFAULT 30,"active" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "AvailabilityRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Holiday" ("id" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"date" DATE NOT NULL,"label" TEXT,CONSTRAINT "Holiday_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BlockedSlot" ("id" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"date" DATE NOT NULL,"time" TEXT NOT NULL,CONSTRAINT "BlockedSlot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Appointment" ("id" TEXT NOT NULL,"bookingId" TEXT NOT NULL,"doctorId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"serviceId" TEXT NOT NULL,"consultationType" TEXT NOT NULL,"localDate" TEXT NOT NULL,"localTime" TEXT NOT NULL,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"timezone" TEXT NOT NULL,"status" "AppointmentStatus" NOT NULL DEFAULT 'PENDING',"paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'NOT_REQUIRED',"concern" TEXT,"notes" TEXT,"meetingUrl" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AppointmentStatusHistory" ("id" TEXT NOT NULL,"appointmentId" TEXT NOT NULL,"fromStatus" "AppointmentStatus","toStatus" "AppointmentStatus" NOT NULL,"reason" TEXT,"changedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AppointmentStatusHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL,"appointmentId" TEXT NOT NULL,"amount" INTEGER NOT NULL,"status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',"provider" TEXT,"providerRef" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentTransaction" ("id" TEXT NOT NULL,"paymentId" TEXT NOT NULL,"event" TEXT NOT NULL,"providerRef" TEXT,"payload" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PaymentTransaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"appointmentId" TEXT,"channel" "NotificationChannel" NOT NULL,"status" "NotificationStatus" NOT NULL DEFAULT 'QUEUED',"subject" TEXT NOT NULL,"body" TEXT NOT NULL,"attempts" INTEGER NOT NULL DEFAULT 0,"lastError" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationLog" ("id" TEXT NOT NULL,"notificationId" TEXT NOT NULL,"status" "NotificationStatus" NOT NULL,"providerRef" TEXT,"error" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ReminderJob" ("id" TEXT NOT NULL,"appointmentId" TEXT NOT NULL,"channel" "NotificationChannel" NOT NULL,"runAt" TIMESTAMP(3) NOT NULL,"status" "NotificationStatus" NOT NULL DEFAULT 'QUEUED',"attempts" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "ReminderJob_pkey" PRIMARY KEY ("id"));
CREATE TABLE "MedicalDocument" ("id" TEXT NOT NULL,"appointmentId" TEXT NOT NULL,"patientId" TEXT NOT NULL,"storageKey" TEXT NOT NULL,"originalName" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"sizeBytes" INTEGER NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "MedicalDocument_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ConsultationNote" ("id" TEXT NOT NULL,"appointmentId" TEXT NOT NULL,"content" TEXT NOT NULL,"followUp" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ConsultationNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Prescription" ("id" TEXT NOT NULL,"appointmentId" TEXT NOT NULL,"storageKey" TEXT NOT NULL,"originalName" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Prescription_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ContactEnquiry" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"phone" TEXT,"subject" TEXT NOT NULL,"message" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ContactEnquiry_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"userId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SystemSetting" ("id" TEXT NOT NULL,"key" TEXT NOT NULL,"value" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SystemSetting_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "PatientProfile_userId_key" ON "PatientProfile"("userId");
CREATE UNIQUE INDEX "DoctorProfile_userId_key" ON "DoctorProfile"("userId");
CREATE UNIQUE INDEX "AvailabilityRule_doctorId_weekday_key" ON "AvailabilityRule"("doctorId","weekday");
CREATE UNIQUE INDEX "Holiday_doctorId_date_key" ON "Holiday"("doctorId","date");
CREATE UNIQUE INDEX "BlockedSlot_doctorId_date_time_key" ON "BlockedSlot"("doctorId","date","time");
CREATE UNIQUE INDEX "Appointment_bookingId_key" ON "Appointment"("bookingId");
CREATE INDEX "Appointment_patientId_startsAt_idx" ON "Appointment"("patientId","startsAt");
CREATE INDEX "Appointment_doctorId_startsAt_idx" ON "Appointment"("doctorId","startsAt");
CREATE INDEX "Appointment_status_startsAt_idx" ON "Appointment"("status","startsAt");
CREATE UNIQUE INDEX "Appointment_doctorId_localDate_localTime_key" ON "Appointment"("doctorId","localDate","localTime");
CREATE UNIQUE INDEX "Payment_appointmentId_key" ON "Payment"("appointmentId");
CREATE INDEX "Notification_status_createdAt_idx" ON "Notification"("status","createdAt");
CREATE INDEX "ReminderJob_status_runAt_idx" ON "ReminderJob"("status","runAt");
CREATE UNIQUE INDEX "ReminderJob_appointmentId_channel_runAt_key" ON "ReminderJob"("appointmentId","channel","runAt");
CREATE UNIQUE INDEX "ConsultationNote_appointmentId_key" ON "ConsultationNote"("appointmentId");
CREATE UNIQUE INDEX "Prescription_appointmentId_key" ON "Prescription"("appointmentId");
CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity","entityId");
CREATE UNIQUE INDEX "SystemSetting_key_key" ON "SystemSetting"("key");

ALTER TABLE "PatientProfile" ADD CONSTRAINT "PatientProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DoctorProfile" ADD CONSTRAINT "DoctorProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AvailabilityRule" ADD CONSTRAINT "AvailabilityRule_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "DoctorProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Holiday" ADD CONSTRAINT "Holiday_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "DoctorProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BlockedSlot" ADD CONSTRAINT "BlockedSlot_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "DoctorProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_doctorId_fkey" FOREIGN KEY ("doctorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AppointmentStatusHistory" ADD CONSTRAINT "AppointmentStatusHistory_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentTransaction" ADD CONSTRAINT "PaymentTransaction_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NotificationLog" ADD CONSTRAINT "NotificationLog_notificationId_fkey" FOREIGN KEY ("notificationId") REFERENCES "Notification"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReminderJob" ADD CONSTRAINT "ReminderJob_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MedicalDocument" ADD CONSTRAINT "MedicalDocument_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConsultationNote" ADD CONSTRAINT "ConsultationNote_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Prescription" ADD CONSTRAINT "Prescription_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
