import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getServerSession, apiServerFetch } from '@/lib/api/server';
import { SignOutButton } from '@/components/sign-out-button';

export const dynamic = 'force-dynamic';

type DoctorAppointment = any; // eslint-disable-line @typescript-eslint/no-explicit-any

export default async function DoctorDashboard() { const session = await getServerSession(); if (!session || session.role !== 'DOCTOR') redirect('/doctor/login'); const [appointmentsData, home] = await Promise.all([apiServerFetch<{ appointments: DoctorAppointment[] }>('/api/appointments'), apiServerFetch<{ demoMode: boolean }>('/api/public/home')]); const appointments=appointmentsData?.appointments||[]; const demoMode=home?.demoMode||false; const completed=appointments.filter(item=>item.status==='COMPLETED').length; return <div className="dash"><div className="dashbar"><div className="container nav"><Link className="brand" href="/"><span className="mark">R</span>Dr. Rashida Ahmad</Link><div className="actions"><span>{session.name}</span><SignOutButton /></div></div></div><main className="container dashmain"><div className="eyebrow">Doctor portal</div><h1 style={{fontSize:48,marginTop:12}}>Good morning, Dr. Rashida.</h1>{demoMode && <div className="demo" style={{marginTop:22,borderRadius:6}}>Demo/Test Mode · provider calls are sandboxed</div>}<div className="stats"><div className="stat"><span>Today's appointments</span><strong>{appointments.filter(item=>item.localDate===new Date().toISOString().slice(0,10)).length}</strong></div><div className="stat"><span>Upcoming</span><strong>{appointments.filter(item=>['PENDING','CONFIRMED'].includes(item.status)).length}</strong></div><div className="stat"><span>Completed</span><strong>{completed}</strong></div><div className="stat"><span>Cancelled / no show</span><strong>{appointments.filter(item=>['CANCELLED','NO_SHOW'].includes(item.status)).length}</strong></div></div><section className="list-card"><div className="section-head"><div><div className="eyebrow">Live appointment feed</div><h2 style={{fontSize:32,marginTop:8}}>Appointments</h2></div><span className="badge">{appointments.length} records</span></div>{appointments.length ? appointments.map(item=><div className="appointment" key={item.id}><div><b>{item.patient.name}</b><br/><small className="muted">{item.service.name} · {item.localDate} at {item.localTime} IST<br/>{item.patient.email}</small></div><div><span className="badge">{item.status}</span><br/><small className="muted">{item.bookingId}</small></div></div>) : <p className="muted">No appointments have been booked.</p>}</section></main></div>; }
